### ISSUE TITLE
Provide spacing between buttons on a horizontal list

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/design-vanilla-framework#291]
When using multiple buttons next to each other as a list in one row, it will be good to provide a standard space between the elements as right now they are quite next to each other breaking the grid established on the vanilla layout:

## Current 
![image](https://user-images.githubusercontent.com/8167677/42634014-047a61e4-85da-11e8-81a8-6e3c4f508586.png)

## Proposed
![image](https://user-images.githubusercontent.com/8167677/42634100-384fcc3e-85da-11e8-9214-ac4717418eff.png)

**Comment by kwm14** [comment]
## Agreed in WG
- @anthonydillon to provide CodePen example as we can't replicate this issue
- By default `button` next to `button` should have `1rem` spacing to the right
- @therealjuan what's the reason for putting 2 buttons in a list?

**Comment by anthonydillon** [comment]
Codepen example: https://codepen.io/anthonydillon/pen/ajJQPK?editors=1100

**Comment by therealjuan** [comment]
> @therealjuan what's the reason for putting 2 buttons in a list?
It just means that they are laid out horizontally like on a sticky nav bar

**Comment by deadlight** [comment]
Buttons placed next to each other now have correct horizontal spacing
