### ISSUE TITLE
Breadcrumb component enhancement

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#293]
_Notes from our Product consistency workshop:_

- Not only have soft links
- Juju GUI path/model switcher
- Snaps page

**Comment by kwm14** [comment]
### Vanilla breadcrumb
![screen shot 2018-07-13 at 14 54 04](https://user-images.githubusercontent.com/17748020/42695246-aa8ea0f4-86ac-11e8-951c-fc2d922f44cd.png)

### Juju GUI path
![screen shot 2018-07-13 at 14 54 59](https://user-images.githubusercontent.com/17748020/42695274-c1dff668-86ac-11e8-806c-af3b6d227f6f.png)

**Comment by bartaz** [comment]
Doesn't seem to be relaveant anymore
