### ISSUE TITLE
Look at use of horizontal rules

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#320]
Discussed in weekly Design review with @spencerbygraves @lyubomir-popov @anasereijo 
- use of lines between strips when a background colour is used
- rules when to use lines to divide content
- examples of where we use horizontal rules
  - marketing websites
  - cloud applications

**Comment by matthewpaulthomas** [comment]
> use of lines between strips when a background colour is used

I raised the issue of too many horizontal rules, on a snapcraft.io page, three days earlier in [snapcraft-design#544](https://github.com/CanonicalLtd/snapcraft-design/issues/544). If this discussion was prompted by that issue, then it’s worth pointing out that that page does not use a background colour.

**Comment by kwm14** [comment]
@matthewpaulthomas yes this was raised due to horizontal rules on snapcraft.io. Thanks for pointing me to your issue for reference 😄

**Comment by lyubomir-popov** [comment]
There's an [epic](https://github.com/CanonicalLtd/snap-squad/issues/733) on snapcraft design that will look at this issue; I will cross link any mockups / examples here as well.

**Comment by kwm14** [comment]
Perfect. Thanks @lyubomir-popov 👍

**Comment by bartaz** [comment]
Vanilla doesn't mandate the use of horizontal rules. We can close it for now.
