### ISSUE TITLE
Design secondary header component

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#371]
_Originally filed [here](https://github.com/canonical-websites/vanillaframework.io/issues/194) by @matthewpaulthomas_ 

## Proposal
Introduce a secondary header component as it doesn't currently exist. We have inconsistencies across different sites / applications using this pattern.

**ubuntu.com**
![screenshot 2019-01-28 at 09 48 39](https://user-images.githubusercontent.com/17748020/51827758-01d1f100-22e2-11e9-8535-a09336b942b7.png)

**design.ubuntu.com**
![screenshot 2019-01-28 at 09 48 49](https://user-images.githubusercontent.com/17748020/51827771-08f8ff00-22e2-11e9-98dd-d52eeed93945.png)

**MAAS**
![screenshot 2019-01-28 at 09 50 18](https://user-images.githubusercontent.com/17748020/51827826-25953700-22e2-11e9-92fc-29c2dd781bee.png)

@matthewpaulthomas if you know of any other examples please feel free to add to this issue 😄

**Comment by bartaz** [comment]
@clagom @spencerbygraves Do we think this is still something Vanilla should design?

**Comment by bartaz** [comment]
This is an old issue that should be discussed on the design working group.

**Comment by clagom** [comment]
Duplicate, already discussed in other issues

**Comment by elioqoshi** [comment]
Related to: #814
