### ISSUE TITLE
Shortlist example frameworks

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#405]

**Comment by lyubomir-popov** [comment]
I'm going to jot down some notes here as I research the topic.

Bootstrap: Colour theming is done at build time by just overriding the color variables, doesn't seem to allow different themes within the same build. https://bootstrap.build/app

**Comment by lyubomir-popov** [comment]
[Material design theming](https://codelabs.developers.google.com/codelabs/mdc-103-web/#2) seems to start with a default theme, then override, so the two themes can coexist.

**Comment by lyubomir-popov** [comment]
In terms of requirements:
- In its simplest form, we should be able to switch a pattern to a dark theme by applying a class to it
- A slightly better version, but with possibly more complexity, would be to be able to apply the theme simultaneously to multiple items, like a parent with .is-dark class
- If the current (white theme) is a default that gets overriden with a different theme, would that cause issues when you have nesting? E.g. white card inside dark p-strip
