### ISSUE TITLE
Create tabs template for JS example

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#408]
Look at other Dev tool and framework examples to see how they display code information.

**Comment by kwm14** [comment]
## Examples

[JS Bin
](https://jsbin.com/?html,output)
<img width="1440" alt="Screenshot 2019-08-21 at 09 46 03" src="https://user-images.githubusercontent.com/17748020/63418366-df78ff80-c3fa-11e9-91fb-df6a93f9bd27.png">

[Polaris Shopify](https://polaris.shopify.com/components/actions/button#navigation)

<img width="1440" alt="Screenshot 2019-08-21 at 09 52 04" src="https://user-images.githubusercontent.com/17748020/63418513-21a24100-c3fb-11e9-903a-b3a89d00fb0c.png">

[Ant Design
](https://ant.design/components/dropdown/)

<img width="1440" alt="Screenshot 2019-08-21 at 09 55 25" src="https://user-images.githubusercontent.com/17748020/63418605-4d252b80-c3fb-11e9-8509-609dcbad3011.png">

[Material Design
](https://material-components.github.io/material-components-web-catalog/#/component/button?type=text)

<img width="1429" alt="Screenshot 2019-08-21 at 10 02 03" src="https://user-images.githubusercontent.com/17748020/63418646-5f06ce80-c3fb-11e9-989c-6c9be2bbcb23.png">

[MongoDB](http://mongodb.design/#/ui-design-system/components/view-modal)

<img width="1440" alt="Screenshot 2019-08-21 at 10 16 16" src="https://user-images.githubusercontent.com/17748020/63419456-c2ddc700-c3fc-11e9-900a-860b3a0f9db9.png">

**Comment by kwm14** [comment]
## Design exploration
Few explorations to toggle between our code examples for HTML and JavaScript applied to components that need JS functionality.

Which currently is:
- Accordion
- Code copyable
- Contextual menu
- List Tree
- Modal
- Sub navigation
- Notifications

### 001 - Tabs
![js-docs-example-001a](https://user-images.githubusercontent.com/17748020/63440136-38f72380-c427-11e9-8f68-421782335c35.png)

### 002 - Buttons
![js-docs-example-002a](https://user-images.githubusercontent.com/17748020/63440191-49a79980-c427-11e9-8ecc-b475941ccdaa.png)

### 003 - Switch
![js-docs-example-003a](https://user-images.githubusercontent.com/17748020/63440682-33e6a400-c428-11e9-919a-1b5645c736d8.png)

### 004 - Accordion
![js-docs-example-004a](https://user-images.githubusercontent.com/17748020/63440261-6b088580-c427-11e9-8ba2-5ab0fcd0f59e.png)

**Comment by kwm14** [comment]
Ready for review from UX and Design when you have a spare minute @therealjuan @lyubomir-popov 😉

**Comment by therealjuan** [comment]
My vote goes to

...🥁🥁🥁 drum roll 🥁🥁🥁 ...

↳ `Tabs `

**Comment by lyubomir-popov** [comment]
I'd personally vote for side by side presentation as in codepen:
![image](https://user-images.githubusercontent.com/2741678/63512474-d3b13a00-c4db-11e9-9dba-846c999c2a8e.png)

As reading the js makes more sense to me when I can see where the targeted element is in relation to other markup. 

But I guess it is a personal preference, and people can always do it un their code editor. 
+1 for the tabs.

**Comment by kwm14** [comment]
> I'd personally vote for side by side presentation as in codepen:
> ![image](https://user-images.githubusercontent.com/2741678/63512474-d3b13a00-c4db-11e9-9dba-846c999c2a8e.png)
> 

Not a bad shout having them side-by-side. When we build this in I think it would be to see if we can do this on the documentation site 💯 

But our first pass we be rolling with the tabs layout 👍Design added to build issue https://github.com/canonical-web-and-design/vanilla-squad/issues/679
