### ISSUE TITLE
Design menu button

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#410]
## Implemented in MAAS
![screenshot_5](https://user-images.githubusercontent.com/17748020/61222642-00bb4180-a713-11e9-998d-fe89cfebd78a.png)
![screenshot_6](https://user-images.githubusercontent.com/17748020/61222652-044ec880-a713-11e9-8e0b-3c4258c002fa.png)

**Comment by kwm14** [comment]
## Notes to mention
Recent updates regarding icons in the framework.

- New addition `p-button has-icon` which features the icon on the left.
<img width="178" alt="Screenshot 2019-07-16 at 14 17 11" src="https://user-images.githubusercontent.com/17748020/61297642-8b17aa00-a7d4-11e9-962e-6d61117165b6.png">

- We made a conscious a decision to move icons to the left that are used in other components `p-accordion`
<img width="358" alt="Screenshot 2019-07-16 at 14 20 12" src="https://user-images.githubusercontent.com/17748020/61297775-d7fb8080-a7d4-11e9-9c90-c2750bb56de6.png">

**Comment by kwm14** [comment]
## Dropdown menu
When designing we must reuse and keep existing styling from other components, so we're re-creating something new if not needed.

We now include the ability to add `p-contextual-menu` to buttons as well as links.
<img width="187" alt="Screenshot 2019-07-16 at 14 21 27" src="https://user-images.githubusercontent.com/17748020/61297966-493b3380-a7d5-11e9-9441-b55211abb3de.png">

Sub-navigation was a new addition which also features a toggle menu to open and close, which inherits consistent style except for hover which is coupled with navigation.
<img width="312" alt="Screenshot 2019-07-16 at 14 24 46" src="https://user-images.githubusercontent.com/17748020/61298243-ca92c600-a7d5-11e9-810f-eff5db92d42c.png">

**Comment by kwm14** [comment]
## Initial design
First exploration using existing Vanilla styles and MAAS implementation.
- Default on the left and applied to MAAS on the right
- @spencerbygraves ready for review 👍 

### 001
![002-dropdown-button](https://user-images.githubusercontent.com/17748020/61304179-a5f01b80-a7e0-11e9-8f66-187772432828.png)

**Comment by matthewpaulthomas** [comment]
> We made a conscious a decision to move icons to the left that are used in other components
> - New addition p-button has-icon which features the icon on the left.

That’s good. However, a menubutton’s triangle/chevron symbol is not an “icon” in this sense. Consider that a menubutton might reasonably have an icon _as well as_ the triangle/chevron symbol:

[ ➕ Add ▾ ] [ Modify ▾ ]

In every toolkit that I know of, any menubutton symbol is on the right, regardless of whether it also has an icon.

> We now include the ability to add `p-contextual-menu` to buttons as well as links.

[“Contextual menu” is another name for a context menu](https://en.wikipedia.org/wiki/Contextual_menu) — that is, the kind of menu usually opened by right-clicking, which contains items relating to the object you clicked on. It’s a (small) barrier to understanding Vanilla that it uses the term “contextual menu” to mean something different. Ideally this would be deprecated over time, rather than expanding to more controls. Fortunately, [the term “menubutton” is already commonly used](https://www.ecosia.org/search?q=menubutton) for a button that opens a menu when clicked. Perhaps it can be used for the class name here instead?

**Comment by kwm14** [comment]
Thanks for your feedback @matthewpaulthomas 👍 

> That’s good. However, a menubutton’s triangle/chevron symbol is not an “icon” in this sense. Consider that a menubutton might reasonably have an icon as well as the triangle/chevron symbol:

It's an [icon](https://docs.vanillaframework.io/patterns/icons/#standard) in Vanilla which is why referenced it, but like you say it doesn't and may not always be that icon/chevron. I will update the design and move the icon to the right 😃 

> Fortunately, the term “menubutton” is already commonly used for a button that opens a menu when clicked. Perhaps it can be used for the class name here instead? 

Happy to update the name of the newly proposed component from `dropdown-button` to your suggestion `menubutton`, as it's commonly used 👍

**Comment by kwm14** [comment]
## Updated design
Taking feedback into consideration.

### 002
![003-menu-button](https://user-images.githubusercontent.com/17748020/61389539-064e8e00-a8b1-11e9-8b75-db9d25e777c4.png)

**Comment by spencerbygraves** [comment]
@kwm14 thanks, visual looks good.

**Comment by kwm14** [comment]
> But now the + icon has gone to the wrong side. 👎 You were correct to put the icon on the left.

Ah yes, good spot. Will update 👍 

> To solve this I think we need to make a distinction between an _icon_, a custom thing that represents the meaning of an individual control, and a _behaviour symbol_ that conveys how you interact with this type of control. (You might be able to think of a better name than “behaviour symbol”!)

Interesting, you make a valid point 😄 to help us and users of the framework we could pull out “behaviour symbols” into a new section under [icons](https://docs.vanillaframework.io/patterns/icons/). Similarly to how Salesforce do for their [icon](https://docs.vanillaframework.io/patterns/icons/) library. That way we know which icons are to be used for controls/behaviour/actions icons for particular components in the framework 👍

**Comment by kwm14** [comment]
Updated icon position to the left 👍 @matthewpaulthomas 

### 004
![004-menu-button](https://user-images.githubusercontent.com/17748020/61457843-18880500-a961-11e9-9054-a94062c99d4c.png)

**Comment by matthewpaulthomas** [comment]
It’s unusual for a menubutton’s triangle/chevron to flip when the menu is open, but I guess that’s a matter of taste. Good work otherwise.

**Comment by kwm14** [comment]
Thanks. Next steps to create an [MD design spec](https://github.com/canonical-web-and-design/design-vanilla-framework/issues/411) for build 👍
