### ISSUE TITLE
Add 'Email' icon to social icon library

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#424]
_Request to @pmahnke from team curating https://cn.ubuntu.com/_

Add an email social icon to Vanilla, so the team can use to share content via email.
- https://docs.vanillaframework.io/patterns/icons/#social

**Comment by kwm14** [comment]
The current icon on the asset server:

_circa 2015_

<img width="107" alt="Screenshot 2019-08-12 at 15 33 20" src="https://user-images.githubusercontent.com/17748020/62873099-afed3780-bd16-11e9-8cb8-8c502affaaf2.png">

_circa 2016_

<img width="132" alt="Screenshot 2019-08-12 at 15 33 34" src="https://user-images.githubusercontent.com/17748020/62873100-b085ce00-bd16-11e9-84e0-db342cefb2e7.png">

_circa 2018_

<img width="84" alt="Screenshot 2019-08-12 at 15 33 48" src="https://user-images.githubusercontent.com/17748020/62873102-b085ce00-bd16-11e9-8f0d-0d224c09b1e7.png">

None of these really match our current style, will speak with @waynecrosby @marcush to see if they have an updated one, or whether we need to propose a new one to the icon designers 👍

**Comment by kwm14** [comment]
Updated style provided by @waynecrosby in a recent illustration...
- https://assets.ubuntu.com/v1/c4b290c8-Contact+us.svg

<img width="661" alt="Screenshot 2019-11-11 at 14 40 22" src="https://user-images.githubusercontent.com/17748020/68595387-443f7580-0491-11ea-8d0f-4abc71e7ccc3.png">

But we will need to re-look at it at a smaller icon size 👍

**Comment by kwm14** [comment]
@waynecrosby I've updated our social icons to use official brand assets.

<img width="436" alt="Screenshot 2019-11-14 at 10 56 32" src="https://user-images.githubusercontent.com/17748020/68851321-a2f13300-06cd-11ea-9e76-3acdcf8fe650.png">

Now seeing them in situ I don't think the email icon will fit within the social set, maybe we need to revert the icon to fill rather than an outline. What do you think?

![email](https://user-images.githubusercontent.com/17748020/68851412-d16f0e00-06cd-11ea-878a-d2053ecb06d4.png)

**Comment by waynecrosby** [comment]
@kwm14 I think you're right, a solid version will work best to fit with the others. What pixel size are you using?

**Comment by kwm14** [comment]
> @kwm14 I think you're right, a solid version will work best to fit with the others. What pixel size are you using?

👍 `40px`
