### ISSUE TITLE
Define color set for Suru templates

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#427]
## Current strips
Currently, in Vanilla, we have 3 color variations:
- Light
- Dark
- Accent

**Comment by kwm14** [comment]
Templates to create colorways for:

### Home page suru hero template
![hero-004 @64](https://user-images.githubusercontent.com/17748020/67383759-bfdf8e00-f587-11e9-824c-19388854f82b.png)

### Content page suru topped template
![secondary-topped 001 @64](https://user-images.githubusercontent.com/17748020/67386044-25ce1480-f58c-11e9-9575-8e3c214ad734.png)

**Comment by kwm14** [comment]
## First exploration
As discussed in last week's design review @marcushas mentioned moving away from Ubuntu Orange, so as Vanilla's accent color is `#333333` I thought I'd explore that avenue.

Be good to get your thoughts? @marcushas @anasereijo @waynecrosby 

### 001
**Palette - Vanilla**
3-color-gradient - `#666666` | `#333333` | `#000000`

![hero-004 @64 accent v1](https://user-images.githubusercontent.com/17748020/67476417-ebc64680-f64f-11e9-86fd-22349d3573aa.png)

### 002
**Palette - Vanilla**
3-color-gradient - `#333333` | `#111111` | `#000000`

![hero-004 @64 accent v2](https://user-images.githubusercontent.com/17748020/67476418-ec5edd00-f64f-11e9-8c90-13dd0ea491c8.png)

### 003
**Palette - Vanilla x Canonical**
3-color-gradient - `#333333` | `#111111` | `#2C001E`

![hero-004 @64 accent v3](https://user-images.githubusercontent.com/17748020/67476419-ec5edd00-f64f-11e9-9459-4c8a6601f16a.png)

**Comment by waynecrosby** [comment]
@kwm14 I think 001 is the most successful although I think the 'content page' top might need a bit of work. Also, did you try a version with a bit of orange going into grey?

**Comment by anasereijo** [comment]
Hi @kwm14 

Not sure if I shared with you, but we have a dark grey gradient that we developed to use on takeovers and landing pages. Maybe you could use the same gradient instead of creating a new one? The file is [here](https://drive.google.com/open?id=1LsbNZ2xp2ehjCd2KI_ixHgDpBhvYdEIT&authuser=ana.sereijo@canonical.com&usp=drive_fs)

Personally I don't like **003** version. I don't think it works using the aubergine and black/grey.

**Comment by kwm14** [comment]
> @kwm14 I think 001 is the most successful although I think the 'content page' top might need a bit of work. Also, did you try a version with a bit of orange going into grey?

Nice one, this was my preferred version too. I wanted to avoid going too dark otherwise it will look very similar to https://maas.io/ styling.

Haven't tried with Ubuntu Orange as all I could visualize is Halloween, but will give it ago and explore 👍

**Comment by kwm14** [comment]
> Not sure if I shared with you, but we have a dark grey gradient that we developed to use on takeovers and landing pages. Maybe you could use the same gradient instead of creating a new one? See screenshot below and find the file is [here](https://drive.google.com/open?id=1LsbNZ2xp2ehjCd2KI_ixHgDpBhvYdEIT&authuser=ana.sereijo@canonical.com&usp=drive_fs).
> 

Nope, but I will take a look at your file. Thanks for sharing 👍 
> 
> Personally I don't like **003** version. I don't think it works using aubergine and black/grey.

Agree, wanted to explore using Canonical brand colors to tie in with Canonical Web team 😉

**Comment by kwm14** [comment]
## Updated exploration
Updated gradient color-ways based on feedback. Ready for another look when you are @anasereijo @waynecrosby 😃 

### 004
**Palette - Dark Grey Suru**
_assets by @anasereijo_ 
3-color-gradient - `#111111` | `#333333` | `#E4E4E4`

**Homepage**

![hero-004 @64 accent v4](https://user-images.githubusercontent.com/17748020/67490662-7ec0aa00-f66b-11e9-9fb6-736f4e535e07.png)

**Content page**

![secondary-topped 001 @64 accent v4](https://user-images.githubusercontent.com/17748020/67490689-8718e500-f66b-11e9-8656-da3ff0071b6f.png)

### 005
**Palette - Vanilla x Ubuntu**
_suggestion by @waynecrosby_ 
3-color-gradient - `#333333` | `#111111` | `#E95420`

**Homepage**

![hero-004 @64 accent v5](https://user-images.githubusercontent.com/17748020/67490786-b0d20c00-f66b-11e9-9aae-e0acda72499a.png)

**Content page**

![secondary-topped 001 @64 accent v5](https://user-images.githubusercontent.com/17748020/67490903-eb3ba900-f66b-11e9-82ca-ae081fe77e30.png)

### 006
**Palette - Vanilla**
_inspired by preferred 001 using Dark Grey Suru but flipped_ 
3-color-gradient - `#4E4E4D` | `#333333` | `#111111`

**Homepage**

![hero-004 @64 accent v6](https://user-images.githubusercontent.com/17748020/67491015-1c1bde00-f66c-11e9-8a6e-45986541d182.png)

**Content page**

![secondary-topped 001 @64 accent v6](https://user-images.githubusercontent.com/17748020/67491026-2211bf00-f66c-11e9-8ed1-c6766273e5fd.png)

**Comment by waynecrosby** [comment]
@kwm14 Ana & I prefer version 006 ;)

**Comment by kwm14** [comment]
> @kwm14 Ana & I prefer version 006 ;)

Nice one! 👍

**Comment by kwm14** [comment]
Templates and colorways added to [build issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/2539#issuecomment-546388786), with gradient and fold CSS values 👍
