### ISSUE TITLE
Review sidebar navigation across applications

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#438]

**Comment by spencerbygraves** [comment]
I've had a look at how we currently use side navigation. This will help to design a solution that can be used widely.

**Products**

MAAS uses the same navigation as our documentation sites, JAAS and RBAC are similar but differ in the use of icons and text size.

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/11f75597-858f-4006-8d9c-6519c6a54e18)

**Docs**

Largely the same except for the use of background colour in Vanilla.

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/8535f194-ae23-4095-8126-22ff954bf49c)

**Paris sprint 2019**

We looked at this in Paris, some of that work informed the JAAS dashboard navigation.

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/981fe2a4-65e5-4f8a-9600-74d32ce3c9f2)

**Comment by spencerbygraves** [comment]
Previously we had this in Vanilla, but it was deprecated.

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/2a7ca952-9d3e-4ca9-b471-cf1b8a6db0b8)
