### ISSUE TITLE
The active state of the navigation header is too sublte

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/design-vanilla-framework#449]
During our meetings with Mark, he mentioned that on Vanilla level he doesn't think the current active state of the navigation header is clear enough. 
He did mockup this as an example, with the active link on a white background, similar to a tab:
![Screenshot 2020-06-23 at 09.41.35.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/60881b54-da1e-40ef-91ea-3434ea2dcccb)

We might implement this on CharmHub.io first.

Link:
https://docs.google.com/document/d/1JzRjODk3UkZ-y2cg1SdG_RuOqMF0SkqN5uqyIa4G4Ig/edit

**Comment by lyubomir-popov** [comment]
Some thoughts and a proposal. 
https://miro.com/app/board/o9J_kqPIMZQ=/

**Comment by clagom** [comment]
Looks good to me, worth going back and propose it. Do we roughly know when this could happen?

**Comment by spencerbygraves** [comment]
@clagom we looked at this in the design review this morning. We discussed adding the white tab to Charm Hub for Montreal as per Mark's request, and having this in a separate branch to also show as a proposal.

**Comment by lyubomir-popov** [comment]
@clagom I can be ready with the proposal next week. Then maybe we can setup demos of maas.io, snapcraft and charmhub to illustrate it better. It's a couple of lines of css so making a demo pr is trivial.

**Comment by clagom** [comment]
Sounds good. The next Charm Hub meeting will be in the Virtual Montreal, maybe we can setup a session with you then. If not, the proposal can be presented in the next bi-weekly meeting.

**Comment by solazio** [comment]
Please consider medium to large screen sizes where the navigation buttons are wrapped on 2 rows
![image](https://user-images.githubusercontent.com/40214246/86006003-43058d80-ba0d-11ea-97e4-451a71b3cd08.png)

**Comment by lyubomir-popov** [comment]
@solazio By this point the nav should have switched to a mobile responsive version, truncating the les important part of the account email (should it use email to begin with? Why not an alias or user name or something). 

But in case that happens unintendedly - and it has happened before - you're right it should look better. The proposal I'm working on would handle it like this:

![Horisontal-nav-graceful-degradation](https://user-images.githubusercontent.com/2741678/86010633-95e24380-ba13-11ea-8194-8a9d3e6d528a.png)

**Comment by solazio** [comment]
@lyubomir-popov yes, the email will be replaced by an alias or name. In your case the highlighted part works fine, but in my case (full white) it looks very disconnected from the page.

**Comment by lyubomir-popov** [comment]
@solazio I'll make sure we highlight this when we explain why we are proposing an alternative to the full white highlight.

**Comment by lyubomir-popov** [comment]
I've made a case for an alternative treatment of the active page highlight here:
https://zpl.io/bAoJGKp

Please take a look and comment.
