### ISSUE TITLE
Documentation example component reference

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#45]
Follow guidelines created by Matthew which can be found here - https://github.com/ubuntudesign/vanilla-squad/issues/20

This piece of work will feed into Greg's component documentation work.

**Comment by kwm14** [comment]
Example Vanilla component reference doc created by Matthew here: https://docs.google.com/document/d/1gDy8y_EEWfweINfhuxcmN7Ov69FMYNZW3y_Hh_Pu9rM/edit

**Comment by deadlight** [comment]
The vanilla project documentation now includes usage examples for each component.

Any issues with documentation content can be raised as specific bugs.
